name: deploy
on:
  push:
    branches:
      - articles

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: npm i
      - run: pip -V
      - run: pip install -r requirements.txt
      - name : Sync
        uses : JamesIves/github-pages-deploy-action@4.1.7
        with :
          branch : main # action 应该部署到的分支 。
          folder : out #操作应该部署的文件夹 。
          clean: false
          token: ${{ secrets.GIT_ACTION }}
          target-folder: .
